# Generated by Django 5.2.5 on 2025-08-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='stock',
        ),
    ]
